server:
  port: 80
order:
  isOpen: 1

spring:
  profiles:
    active: dev



---

spring:
  profiles: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
     host: localhost
     port: 6379
#     password:
     database: 0
     lettuce:
       pool:
         max-active: 20
         max-wait: -1
         max-idle: 10
         min-idle: 8
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
#          datasource:
#            url: jdbc:mysql://localhost:3306/quartz?serverTimezone=Asia/Shanghai
#            username: root
#            password: 123456
#            driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    jdbc:
     initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true



##异步线程池
#  async:
#    executor:
#      thread:
#        core_pool_size: 10
#        max_pool_size: 50
#        queue_capacity: 1000
#        keep_alive_seconds: 300

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
#  mapper-locations: classpath:org/lqh/home/mapper/xml/*.xml



---
spring:
  profiles: test
  jackson:
    date-format: 年-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8082
---
spring:
  profiles: prd
  jackson:
    date-format: yyyy-月-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8083
